default: &default
  adapter: postgresql
  encoding: utf8
  min_messages: warning
  pool: <%= Integer(ENV.fetch("DB_POOL", 5)) %>

development: 
  <<: *default
  host:     <%= ENV.fetch("DB_HOSTNAME", "") %>
  database: <%= ENV.fetch("DB_DATABASE", "") %>
  username: <%= ENV.fetch("DB_USERNAME", "") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
  
test: 
  <<: *default
  database: crm_test
  username: domster83
  password: ''

production: 
  <<: *default
  encoding: utf8
  host:     <%= ENV.fetch('DB_HOSTNAME', '') %>
  database: <%= ENV.fetch("DB_DATABASE", "") %>
  username: <%= ENV.fetch("DB_USERNAME", "") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
  sslmode: <%= ENV.fetch("DB_SSL_MODE", "") %>
  port: 5432
  min_messages: warning
  pool: <%= [Integer(ENV.fetch("MAX_THREADS", 5)), Integer(ENV.fetch("DB_POOL", 5))].max %>

azure_dev: 
  <<: *default
  host:     <%= ENV.fetch("DB_HOSTNAME", "") %>
  database: <%= ENV.fetch("DB_DATABASE", "") %>
  username: <%= ENV.fetch("DB_USERNAME", "") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
  sslmode: <%= ENV.fetch("DB_SSL_MODE", "" ) %>
  port: 5432
  min_messages: warning
  pool: <%= [Integer(ENV.fetch("MAX_THREADS", 5)), Integer(ENV.fetch("DB_POOL", 5))].max %>
